FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
COPY . /app/

RUN pip install -r requirements.txt

# Exponemos el puerto en el que Flask va a correr
EXPOSE 8080

# Comando para ejecutar tu aplicación Flask
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]
